# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout pkg
        uses: actions/checkout@v2
        with:
          path: package

      - name: Checkout calpath
        uses: actions/checkout@v2
        with:
          repository: figwh/calpath.git
          token: ${{ secrets.MY_REPO }} 
          ref: main
          path: calpath          
      
      - name: Checkout satplan server
        uses: actions/checkout@v2
        with:
          repository: figwh/satplan-server.git
          token: ${{ secrets.MY_REPO }} 
          ref: main
          path: satplan-server

      - name: Checkout satplan web
        uses: actions/checkout@v2
        with:
          repository: figwh/satplan-web.git
          token: ${{ secrets.MY_REPO }}  
          ref: main
          path: satplan-web
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: figwh/satplan:latest

